services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'fatteneder/diff-filter']
    volumes:
      - ".:/plugin:ro"
  tests:
    # image: buildkite/plugin-tester
    build: .
    volumes:
      - ".:/plugin:ro"
