name: Diff Filter
description: Filter build steps based on file diff.
author: https://github.com/fatteneder
requirements: []
configuration:
  properties:
    name:
      type: string
    match:
      type: array
    ignore:
      type: array
    target_branch:
      type: string
  additionalProperties: false
