name: Diff Filter
description: Filter build steps based on file diff.
author: https://github.com/fatteneder
requirements: []
configuration:
  properties:
    name:
      type: string
    match:
      type: array
    ignore:
      type: array
  additionalProperties: false

# steps:
#   - label: launch jobs
#     plugins:
#       - fatteneder/diff-filter#v1:
#         name: docs
#         match:
#           - "doc/**"
#         ignore:
#       - fatteneder/diff-filter#v1:
#         name: build
#         match:
#         ignore:
#           - "doc/**"
#           - "README.md"
#     commands: |
#       if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS} == 1 ]]; then
#           echo "buildkite-agent upload docs.yml"
#       fi
#       if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD} == 1 ]]; then
#           echo "buildkite-agent upload build.yml"
#       fi
