name: Diff Filter
description: Filter build steps based on git file diff.
author: https://github.com/fatteneder
requirements: [git]
configuration:
  properties:
    name:
      type: string
    match:
      type: array
    ignore:
      type: array
    target_branch:
      type: string
  additionalProperties: false
