#!/bin/bash

RESULT=$(source hooks/diff-filter-impl)
NAME="${BUILDKITE_PLUGIN_DIFF_FILTER_NAME^^}" # ^^ for uppercase
TRIGGER_VAR="BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_${NAME}"
echo $TRIGGER_VAR
echo $RESULT
export declare $TRIGGER_VAR=$RESULT
echo ${!TRIGGER_VAR}
