#!/bin/bash

set -ueo pipefail

HOOKS_DIR="$( dirname "${BASH_SOURCE[0]}" )"
cd "$BUILDKITE_BUILD_CHECKOUT_PATH"

RESULT=$("$HOOKS_DIR/diff-filter-impl")
NAME="${BUILDKITE_PLUGIN_DIFF_FILTER_NAME^^}" # ^^ for uppercase
echo "Hello"
echo $NAME
TRIGGER_VAR="BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_${NAME}"
echo "World"
echo $TRIGGER_VAR
echo "Sers"
echo $RESULT
export declare $TRIGGER_VAR=$RESULT
echo "Oida"
echo ${!TRIGGER_VAR}
