#!/bin/bash

set -ueo pipefail

echo "$(pwd)"
HOOKS_DIR="$( dirname "${BASH_SOURCE[0]}" )"
echo "$HOOKS_DIR"
echo "$BUILDKITE_BUILD_CHECKOUT_PATH"
cd "$BUILDKITE_BUILD_CHECKOUT_PATH"
echo "$(pwd)"

RESULT=$("$HOOKS_DIR/diff-filter-impl")
NAME="${BUILDKITE_PLUGIN_DIFF_FILTER_NAME^^}" # ^^ for uppercase
TRIGGER_VAR="BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_${NAME}"
echo $TRIGGER_VAR
echo $RESULT
export declare $TRIGGER_VAR=$RESULT
echo ${!TRIGGER_VAR}
